import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Learn Next Js',
  description: 'Generated by Ashwini'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='mb-6 bg-gray-200 p-4'>
          <nav>
            <ul>
              <li>
                <Link href='/about'>Header</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>

        <footer className='mt-6 bg-gray-200 p-4'>
          <h2>Footer</h2>
        </footer>
      </body>
    </html>
  )
}
