import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@components/layout/header'
import Footer from '@components/layout/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Learn Next Js',
  description: 'Generated by Ashwini'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
